### ISSUE TITLE
Problem with closed world assumption

### ISSUE THREAD

**Issue by meneguzzi** [pucrs-automated-planning/javagp#23] opened 2016-09-16 23:37 UTC
Closed world assumption does not seem to be working on the attached RPG domain (it generates a useless destroy_sword action because it cannot find (not (carry)).
[pb1.txt](https://github.com/pucrs-automated-planning/javagp/files/477844/pb1.txt)
[rpg.txt](https://github.com/pucrs-automated-planning/javagp/files/477843/rpg.txt)

@ guilhermekrz if you have time to check this in detail, I'd appreciate it. No hurry though.

**Comment by Maumagnaguagno** [comment] 2016-09-17 04:09
This issue is related to #14 and #10.
We need to create a minimal example to make debugging easier first.

**Comment by guilhermekrz** [comment] 2016-09-17 13:48
Ok, I think this bug is fixed now. 
@meneguzzi Do you have the domain/problem files from issues #14 and #10, so we can create unit tests, and then close all these three issues?

**Comment by guilhermekrz** [comment] 2016-09-17 13:51
Another thing: I had to comment out the "testRushPDDL", because it was breaking travis (2dca563acf6adfad578b6a19ac601934f04b5f9f).
I don't know if it is a problem of timeout or of jvm memory, but I could not fix it. In my local machine it is working fine.
Maybe we could add these long tests to another target, like: "longTests", so we could run them locally. Or we could make another target like "lightTests", and configure Travis to run these instead. What do you prefer?

**Comment by Maumagnaguagno** [comment] 2016-09-17 20:48
The input files should still be available in sourceforge:
- #14 is [here](https://sourceforge.net/p/emplan/bugs/14/)
- #10 is ??? (I could not find bug 10, perhaps something got destroyed in the transition to GitHub)

But this is not a problem since I did the Aperture domain:
- [Aperture.zip](https://github.com/pucrs-automated-planning/javagp/files/478357/aperture.zip)
- The example from the first post is from pb1.pddl

| Problem | Plan size |
| --- | --- |
| pb1.pddl | 8 |
| pb2.pddl | 10 |
| pb3.pddl | 10 |
| pb4.pddl | 9 |
| pb5.pddl | 12 |
| pb6.pddl | 13 |
| pb7.pddl | 13 |
| pb8.pddl | 20 |
| pb9.pddl | 27 |
| pb10.pddl | 21 |

[Travis does have a timeout](https://docs.travis-ci.com/user/common-build-problems/#My-builds-are-timing-out), but is minutes long, we are around 1 min total currently.
The Rush test is too simple to actually fail, this is why it is named pb0, one car moves only horizontally (branch factor 2) in the board, 4 moves to reach the goal.
I suspect this is some sort of internal timeout (in our tests) or wrong config (perhaps related to memory as you suggested).
I think we should break them in 2 test suites, one that checks parts of the planner and other that actually plans.
Users could benefit on that, but Travis should run both until we reach its time/memory limit.

Thanks @ guilhermekrz, we can actually see things break now :smile: .

**Comment by meneguzzi** [comment] 2016-09-18 20:05
But #10 is there, I just can't find the domain files anywhere, @ramonpereira, do you have it somewhere?

**Comment by Maumagnaguagno** [comment] 2016-09-18 22:15
I expected it to be like https://sourceforge.net/p/emplan/bugs/10/
But it redirects me to a login screen :disappointed:

**Comment by meneguzzi** [comment] 2016-09-18 22:39
Just downloaded the domain from SF, it's attached below.
[aperture.zip](https://github.com/pucrs-automated-planning/javagp/files/479023/aperture.zip)

**Comment by guilhermekrz** [comment] 2016-09-19 12:51
Ok, so for the aperture domain, I got this exception:
```java.lang.IllegalStateException: Exp not expected when parsing Proposition: EQUAL_ATOM
at graphplan.parser.PDDLPlannerAdapter.getPropositionsFromExp(PDDLPlannerAdapter.java:207)```

Is this expected right, because JavaGP currently does not support ":equality"? I tried to get the old jar from sourceforge, but then I got a similar error:
```SEVERE: Parser error at line 3, column 58 file (pb1.pddl) : Require key ":equality" forbidden due to parser requirement options.```

So I think this domain should be linked to a future enhancement when we start supporting this ":equality" requirement. (But how one was able to run this domain using old javagp? Maybe removing all things related to ":equality"? Am I missing something here?)

---

#14: The problem appears to be in the generation of possible actions. As "at(b)" only appears at the goal state, OperatorFactory:getAllPossibleInstantiations() does not return "move(a,b)". I could not find how Strips parser fills this information...

**Comment by Maumagnaguagno** [comment] 2016-09-19 19:43
- Since equality is not supported it should work fine without it (for not equal cases) or throw errors when it is used.
- If a predicate appears in the goal but not in the initial state we could assume it is false in the initial state.

**Comment by meneguzzi** [comment] 2016-09-19 19:50
I don't remember if this happened before too. I was afraid this was a result of a bad interaction between the PDDL4j parser and the Jason logical backend we are using, but it may just be the equality requirement. 
As soon as everyone is back we should briefly review this and decide how to proceed with some of these issues.

Also, you may have noticed that I appended the README.md for the main repository folder, I have put idea sketches on how to deal with many of the requirements we don't currently support.

**Comment by Maumagnaguagno** [comment] 2016-09-19 20:49
Equality is easy to support, just add `(= obj obj)` to the initial state for every object/constant.
The problem is to decide how to deal with action instantiation, should we change it to accept repeated objects as values (so that `(= ?p1 ?p2)` could be true)?
That would make it slower for domains without the proper description, as more instances are possible.

**Comment by meneguzzi** [comment] 2016-09-20 23:16
For JavaGP itself, the problem of more instances is not the main issue (since we are doing lifted planning), but rather, how do we integrate this bit of logic into the logical framework. We could possibly hack something on top of Jason, but maybe it's time we implemented our own logical framework.

**Comment by guilhermekrz** [comment] 2021-12-08 21:48
I was trying to remove this issue from my list of open issues, but editing the comments to mention @ guilhermekrz instead of @guilhermekrz did not work :p 
I'm going to close this now, but we can open another issue if this is still valid

**Closed as completed by guilhermekrz** 2021-12-08 21:48 UTC
Labels: bug

**Comment by meneguzzi** [comment] 2021-12-09 09:19
End of year cleaning?
